version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catastrosaas_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      GUNICORN_WORKERS: 3
    ports:
      - "8001:8001"
    networks:
      - catastrosaas_net

  db:
    image: postgres:15
    container_name: catastrosaas_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - catastrosaas_pgdata:/var/lib/postgresql/data
    networks:
      - catastrosaas_net

networks:
  catastrosaas_net:

volumes:
  catastrosaas_pgdata:
